"""tracks

Revision ID: 520cdfc5c274
Revises: 9271e81ca97a
Create Date: 2024-01-29 19:24:26.305597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520cdfc5c274'
down_revision: Union[str, None] = '9271e81ca97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genre'))
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track'))
    )
    op.create_table('track_to_genre',
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_track_to_genre_genre_id_genre')),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name=op.f('fk_track_to_genre_track_id_track'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_to_genre')
    op.drop_table('track')
    op.drop_table('genre')
    # ### end Alembic commands ###
